spring.application.name=examen-mapreduce

server.port=8080
server.name=${SERVER_NAME:server-local}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/examenad}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root123}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.initialization-fail-timeout=60000

spring.sql.init.mode=never